"""init schema

Revision ID: 00b196accbcc
Revises: 
Create Date: 2026-01-17 23:38:04.263909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '00b196accbcc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patchpanels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    op.create_index(op.f('ix_patchpanels_id'), 'patchpanels', ['id'], unique=False)
    op.create_table('switches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('total_ports', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('place', sa.String(length=100), nullable=True),
    sa.Column('Mac', sa.String(length=100), nullable=True),
    sa.Column('IP', sa.String(length=100), nullable=True),
    sa.Column('Notes', sa.String(length=120), nullable=True),
    sa.Column('show', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    op.create_index(op.f('ix_switches_id'), 'switches', ['id'], unique=False)
    op.create_table('ports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=50), nullable=True),
    sa.Column('port_number', sa.Integer(), nullable=True),
    sa.Column('switch_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['switch_id'], ['switches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id'),
    sa.UniqueConstraint('unique_id')
    )
    op.create_index(op.f('ix_ports_id'), 'ports', ['id'], unique=False)
    op.create_table('switch_patch_panel',
    sa.Column('switch_id', sa.Integer(), nullable=False),
    sa.Column('patch_panel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patch_panel_id'], ['patchpanels.id'], ),
    sa.ForeignKeyConstraint(['switch_id'], ['switches.id'], ),
    sa.PrimaryKeyConstraint('switch_id', 'patch_panel_id')
    )
    op.create_table('patch_panel_ports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('port_number', sa.Integer(), nullable=True),
    sa.Column('patch_panel_id', sa.Integer(), nullable=True),
    sa.Column('switch_port_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patch_panel_id'], ['patchpanels.id'], ),
    sa.ForeignKeyConstraint(['switch_port_id'], ['ports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_DEVICES_id'), table_name='DEVICES')
    op.drop_table('DEVICES')
    op.alter_column('devices', 'name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('devices', 'place',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('devices', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('devices', 'Date',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index(op.f('IP'), table_name='devices')
    op.drop_index(op.f('Mac'), table_name='devices')
    op.drop_index(op.f('ix_DEVICES_id'), table_name='devices')
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.create_index(op.f('ix_DEVICES_id'), 'devices', ['id'], unique=False)
    op.create_index(op.f('Mac'), 'devices', ['Mac'], unique=True)
    op.create_index(op.f('IP'), 'devices', ['IP'], unique=True)
    op.alter_column('devices', 'Date',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('devices', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('devices', 'place',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               nullable=False)
    op.alter_column('devices', 'name',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               nullable=False)
    op.create_table('DEVICES',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('model', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('floor', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('place', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('cableNumber', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Mac', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('IP', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Notes', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('show', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('Date', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb3_general_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_DEVICES_id'), 'DEVICES', ['id'], unique=False)
    op.drop_table('patch_panel_ports')
    op.drop_table('switch_patch_panel')
    op.drop_index(op.f('ix_ports_id'), table_name='ports')
    op.drop_table('ports')
    op.drop_index(op.f('ix_switches_id'), table_name='switches')
    op.drop_table('switches')
    op.drop_index(op.f('ix_patchpanels_id'), table_name='patchpanels')
    op.drop_table('patchpanels')
    # ### end Alembic commands ###
