"""add title to patch_panel_ports & ports

Revision ID: 9e41caf6a660
Revises: d245d3eb8b5a
Create Date: 2026-01-18 01:21:10.618328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e41caf6a660'
down_revision: Union[str, Sequence[str], None] = 'd245d3eb8b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patch_panel_ports', sa.Column('title', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'patch_panel_ports', ['title'])
    op.add_column('ports', sa.Column('title', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ports', 'title')
    op.drop_constraint(None, 'patch_panel_ports', type_='unique')
    op.drop_column('patch_panel_ports', 'title')
    # ### end Alembic commands ###
