"""sync schema after manual title column

Revision ID: accc728c2d89
Revises: 9e41caf6a660
Create Date: 2026-01-18 01:26:45.009603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'accc728c2d89'
down_revision: Union[str, Sequence[str], None] = '9e41caf6a660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patch_panel_ports', 'title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_index(op.f('title'), table_name='patchpanels')
    op.add_column('ports', sa.Column('title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ports', 'title')
    op.create_index(op.f('title'), 'patchpanels', ['title'], unique=True)
    op.alter_column('patch_panel_ports', 'title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
