"""init schema

Revision ID: d245d3eb8b5a
Revises: 00b196accbcc
Create Date: 2026-01-17 23:55:55.603157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd245d3eb8b5a'
down_revision: Union[str, Sequence[str], None] = '00b196accbcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patchpanels', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('patchpanels', sa.Column('show', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'patchpanels', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patchpanels', type_='unique')
    op.drop_column('patchpanels', 'show')
    op.drop_column('patchpanels', 'title')
    # ### end Alembic commands ###
